[build]
command = "hugo --source site --gc --minify --destination ../public"
publish = "public"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
NODE_ENV = "PRODUCTION"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --source site --destination ../public --gc --minify --buildDrafts --buildFuture --baseUrl $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"
NODE_ENV = "PRODUCTION"

[template.environment]
STATUSKIT_PAGE_TITLE = "title for the page"
STATUSKIT_COMPANY_LOGO = "url to your company's logo"
STATUSKIT_SUPPORT_CONTACT_LINK = "url to your support page"
STATUSKIT_RESOURCES_LINK = "url to your knowledge base page"
