baseurl = "/"
languageCode = "en-us"
title = "AGRC System Status"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "/images/agrc.svg"
  faviconsPath = "https://gis.utah.gov/images/favicon.ico?"

systems = ["discover", "SDE", "license manager", "gis.utah.gov", "web api", "mapserv"]
