baseurl = "/"
languageCode = "en-us"
title = "UGRC System Status"
theme = "statuskit"
googleAnalytics = "UA-11849964-59"

[permalinks]
incidents = "/incidents/:year/:month/:day/:slug/"

[params]
DateForm = "2006 Jan 02 3:04 PM"
defaultLogo = "/images/ugrc.svg"
faviconsPath = "https://gis.utah.gov/images/favicon.ico?"

systems = [
  "discover",
  "open sgid",
  "license manager",
  "gis.utah.gov",
  "web api",
  "mapserv",
  "vrs gps network",
]

[security]
[security.funcs]
getenv = ['^STATUSKIT_']
